### PR TITLE
Fit Typst package requirements

### PR DESCRIPTION
**Pull request by Cinea4678**
This is an amazing project. As someone who has been using typst as my primary writing tool since its birth, I am delighted to see that Tongji University has such a project which I will be able to use for my undergraduate degree next year.

I noticed that this project needed help #2 , so I referenced an excellent typst project [from another school](https://github.com/csimide/SEU-Typst-Template) and tweaked the structure of this project to make it usable via the `typst init` command and to conform to typst's project structure requirements.

It's worth noting that I've only spent a short amount of time on this thing, so there may be omissions or things that don't meet the expectations of the project maintainers. If is the case, feel free to edit my fork.

Finally, please note that when releasing the project to the typst package registry or test `typst init` locally, you need to replace the import on line 1 in `init-files/tongjithesis.typ` and `init-files/section/*.typ` with:

```
#import ‘@preview/tongji-undergrad-thesis:0.1.1’:*
```

### CODE REVIEW

**Comment by RizhongLin** [comment]
Hello,

Thank you very much for your kind Pull Request. @xbunax is working on this today. @xbunax, could you please verify if this aligns with our goals for today and provide some insights? Thanks!

**Comment by xbunax** [comment]
> Hello,
> 
> Thank you very much for your kind Pull Request. @xbunax is working on this today. @xbunax, could you please verify if this aligns with our goals for today and provide some insights? Thanks!

yes , I need to test this pr. And we need to change the variable name in `tongjithesis.typ` to meet the typst pacmage standard. I have made the change.

**Comment by xbunax** [comment]
> This is an amazing project. As someone who has been using typst as my primary writing tool since its birth, I am delighted to see that Tongji University has such a project which I will be able to use for my undergraduate degree next year.
> 
> I noticed that this project needed help #2 , so I referenced an excellent typst project [from another school](https://github.com/csimide/SEU-Typst-Template) and tweaked the structure of this project to make it usable via the `typst init` command and to conform to typst's project structure requirements.
> 
> It's worth noting that I've only spent a short amount of time on this thing, so there may be omissions or things that don't meet the expectations of the project maintainers. If is the case, feel free to edit my fork.
> 
> Finally, please note that when releasing the project to the typst package registry or test `typst init` locally, you need to replace the import on line 1 in `init-files/tongjithesis.typ` and `init-files/section/*.typ` with:
> 
> ```
> #import ‘@preview/tongji-undergrad-thesis:0.1.1’:*
> ```

Are you test your package in local ? I find I was unable to compile with my env. It seems the `typst.toml` and import path have some problem
```
[14:40:56] compiling ...
watching main.typ
writing to main.pdf

[14:40:56] compiled with errors

error: failed to load file (access denied)
  ┌─ tongjithesis.typ:1:8
  │
1 │ #import "../tongji-undergrad-thesis/elements.typ": *
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │
  = hint: cannot read file outside of project root
  = hint: you can adjust the project root with the --root argument

help: error occurred while importing this module
  ┌─ main.typ:1:8
  │
1 │ #import "./tongjithesis.typ": *

```

**Comment by Cinea4678** [comment]
> > This is an amazing project. As someone who has been using typst as my primary writing tool since its birth, I am delighted to see that Tongji University has such a project which I will be able to use for my undergraduate degree next year.
> > I noticed that this project needed help #2 , so I referenced an excellent typst project [from another school](https://github.com/csimide/SEU-Typst-Template) and tweaked the structure of this project to make it usable via the `typst init` command and to conform to typst's project structure requirements.
> > It's worth noting that I've only spent a short amount of time on this thing, so there may be omissions or things that don't meet the expectations of the project maintainers. If is the case, feel free to edit my fork.
> > Finally, please note that when releasing the project to the typst package registry or test `typst init` locally, you need to replace the import on line 1 in `init-files/tongjithesis.typ` and `init-files/section/*.typ` with:
> > ```
> > #import ‘@preview/tongji-undergrad-thesis:0.1.1’:*
> > ```
> 
> Are you test your package in local ? I find I was unable to compile with my env. It seems the `typst.toml` and import path have some problem
> 
> ```
> [14:40:56] compiling ...
> watching main.typ
> writing to main.pdf
> 
> [14:40:56] compiled with errors
> 
> error: failed to load file (access denied)
>   ┌─ tongjithesis.typ:1:8
>   │
> 1 │ #import "../tongji-undergrad-thesis/elements.typ": *
>   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   │
>   = hint: cannot read file outside of project root
>   = hint: you can adjust the project root with the --root argument
> 
> help: error occurred while importing this module
>   ┌─ main.typ:1:8
>   │
> 1 │ #import "./tongjithesis.typ": *
> ```

Hi😊 I think the hint is clear: please specify the root dir. You may try:

```
typst watch init-files/main.typ --root .
```

**Comment by xbunax** [comment]
> > > This is an amazing project. As someone who has been using typst as my primary writing tool since its birth, I am delighted to see that Tongji University has such a project which I will be able to use for my undergraduate degree next year.
> > > I noticed that this project needed help #2 , so I referenced an excellent typst project [from another school](https://github.com/csimide/SEU-Typst-Template) and tweaked the structure of this project to make it usable via the `typst init` command and to conform to typst's project structure requirements.
> > > It's worth noting that I've only spent a short amount of time on this thing, so there may be omissions or things that don't meet the expectations of the project maintainers. If is the case, feel free to edit my fork.
> > > Finally, please note that when releasing the project to the typst package registry or test `typst init` locally, you need to replace the import on line 1 in `init-files/tongjithesis.typ` and `init-files/section/*.typ` with:
> > > ```
> > > #import ‘@preview/tongji-undergrad-thesis:0.1.1’:*
> > > ```
> > 
> > 
> > Are you test your package in local ? I find I was unable to compile with my env. It seems the `typst.toml` and import path have some problem
> > ```
> > [14:40:56] compiling ...
> > watching main.typ
> > writing to main.pdf
> > 
> > [14:40:56] compiled with errors
> > 
> > error: failed to load file (access denied)
> >   ┌─ tongjithesis.typ:1:8
> >   │
> > 1 │ #import "../tongji-undergrad-thesis/elements.typ": *
> >   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   │
> >   = hint: cannot read file outside of project root
> >   = hint: you can adjust the project root with the --root argument
> > 
> > help: error occurred while importing this module
> >   ┌─ main.typ:1:8
> >   │
> > 1 │ #import "./tongjithesis.typ": *
> > ```
> 
> Hi😊 I think the hint is clear: please specify the root dir. You may try:
> 
> ```
> typst watch init-files/main.typ --root .
> ```

yes , It works. But as a package ,you need to use `ln -s` to your local typst package store path. You can see this https://github.com/typst/packages?tab=readme-ov-file#local-packages

**Comment by Cinea4678** [comment]
> > > > This is an amazing project. As someone who has been using typst as my primary writing tool since its birth, I am delighted to see that Tongji University has such a project which I will be able to use for my undergraduate degree next year.
> > > > I noticed that this project needed help #2 , so I referenced an excellent typst project [from another school](https://github.com/csimide/SEU-Typst-Template) and tweaked the structure of this project to make it usable via the `typst init` command and to conform to typst's project structure requirements.
> > > > It's worth noting that I've only spent a short amount of time on this thing, so there may be omissions or things that don't meet the expectations of the project maintainers. If is the case, feel free to edit my fork.
> > > > Finally, please note that when releasing the project to the typst package registry or test `typst init` locally, you need to replace the import on line 1 in `init-files/tongjithesis.typ` and `init-files/section/*.typ` with:
> > > > ```
> > > > #import ‘@preview/tongji-undergrad-thesis:0.1.1’:*
> > > > ```
> > > 
> > > 
> > > Are you test your package in local ? I find I was unable to compile with my env. It seems the `typst.toml` and import path have some problem
> > > ```
> > > [14:40:56] compiling ...
> > > watching main.typ
> > > writing to main.pdf
> > > 
> > > [14:40:56] compiled with errors
> > > 
> > > error: failed to load file (access denied)
> > >   ┌─ tongjithesis.typ:1:8
> > >   │
> > > 1 │ #import "../tongji-undergrad-thesis/elements.typ": *
> > >   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   │
> > >   = hint: cannot read file outside of project root
> > >   = hint: you can adjust the project root with the --root argument
> > > 
> > > help: error occurred while importing this module
> > >   ┌─ main.typ:1:8
> > >   │
> > > 1 │ #import "./tongjithesis.typ": *
> > > ```
> > 
> > 
> > Hi😊 I think the hint is clear: please specify the root dir. You may try:
> > ```
> > typst watch init-files/main.typ --root .
> > ```
> 
> yes , It works. But as a package ,you need to use `ln -s` to your local typst package store path. You can see this https://github.com/typst/packages?tab=readme-ov-file#local-packages

of course😊, and as I mentioned, you may replace the import in `init-files/tongjithesis.typ` and `init-files/section/*.typ` after `ln -s` to your local typst package store path, and test `typst init` locally. The `../` syntax is used for compatibility with `git clone` usage. 

I leave `../` syntax in this repo because replacing the import is commonly the responsibility of maintainer when they are putting their template into `https://github.com/typst/packages`.

**Comment by xbunax** [comment]
> > > > > This is an amazing project. As someone who has been using typst as my primary writing tool since its birth, I am delighted to see that Tongji University has such a project which I will be able to use for my undergraduate degree next year.
> > > > > I noticed that this project needed help #2 , so I referenced an excellent typst project [from another school](https://github.com/csimide/SEU-Typst-Template) and tweaked the structure of this project to make it usable via the `typst init` command and to conform to typst's project structure requirements.
> > > > > It's worth noting that I've only spent a short amount of time on this thing, so there may be omissions or things that don't meet the expectations of the project maintainers. If is the case, feel free to edit my fork.
> > > > > Finally, please note that when releasing the project to the typst package registry or test `typst init` locally, you need to replace the import on line 1 in `init-files/tongjithesis.typ` and `init-files/section/*.typ` with:
> > > > > ```
> > > > > #import ‘@preview/tongji-undergrad-thesis:0.1.1’:*
> > > > > ```
> > > > 
> > > > 
> > > > Are you test your package in local ? I find I was unable to compile with my env. It seems the `typst.toml` and import path have some problem
> > > > ```
> > > > [14:40:56] compiling ...
> > > > watching main.typ
> > > > writing to main.pdf
> > > > 
> > > > [14:40:56] compiled with errors
> > > > 
> > > > error: failed to load file (access denied)
> > > >   ┌─ tongjithesis.typ:1:8
> > > >   │
> > > > 1 │ #import "../tongji-undergrad-thesis/elements.typ": *
> > > >   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > >   │
> > > >   = hint: cannot read file outside of project root
> > > >   = hint: you can adjust the project root with the --root argument
> > > > 
> > > > help: error occurred while importing this module
> > > >   ┌─ main.typ:1:8
> > > >   │
> > > > 1 │ #import "./tongjithesis.typ": *
> > > > ```
> > > 
> > > 
> > > Hi😊 I think the hint is clear: please specify the root dir. You may try:
> > > ```
> > > typst watch init-files/main.typ --root .
> > > ```
> > 
> > 
> > yes , It works. But as a package ,you need to use `ln -s` to your local typst package store path. You can see this https://github.com/typst/packages?tab=readme-ov-file#local-packages
> 
> of course😊, and as I mentioned, you may replace the import in `init-files/tongjithesis.typ` and `init-files/section/*.typ` after `ln -s` to your local typst package store path, and test `typst init` locally. The `../` syntax is used for compatibility with `git clone` usage.
> 
> I leave `../` syntax in this repo because replacing the import is commonly the responsibility of maintainer when they are putting their template into `https://github.com/typst/packages`.

Ok, I know what's your mean. I solve this , Thanks.

**Comment by Cinea4678** [comment]
The README file has been updated to fit the future change of this project

**Pull request merged**
